# -*- coding: utf-8 -*-
"""Count.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cBVXxzhnu7K4kvDIhp_2CuOWtEnOMoTV
"""

# Importar los módulos necesarios
import spacy
import json
import random
import os
import ast
from google.colab import drive
from spacy.training import Example
from spacy.scorer import Scorer
from spacy.tokens import Doc
from spacy import displacy
!python -m spacy download es_core_news_sm
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize
from google.colab import drive
import ast
import re
import nltk
nltk.download('punkt_tab')

drive.mount('/content/drive')
tfmPath = '/content/drive/MyDrive/TFM'
trainingFilesPath = tfmPath+'/textos_entrenamiento'
valFilesPath = tfmPath+'/texto_validacion'
testFilePath = tfmPath+'/texto_test'

archivo = trainingFilesPath+'/train_forcount.txt'

with open(archivo, 'r', encoding='utf-8') as file:
    content = file.read()

archivo2 = valFilesPath+'/Val_forcount.txt'

with open(archivo2, 'r', encoding='utf-8') as file:
    content2 = file.read()

archivo3 = testFilePath+'/test.txt'

with open(archivo3, 'r', encoding='utf-8') as file:
    content3 = file.read()

def contar_oraciones_con_palabra(texto_input, palabra):
    print("Estadisticas para la palabra: "+palabra)
    oraciones = sent_tokenize(texto_input)

    count = 0
    total_tokens = 0
    total_types = 0
    longitud_oraciones = []

    for oracion in oraciones:
        palabras = word_tokenize(oracion)
        if palabra in palabras:
            count += 1
            num_tokens = len(palabras)
            num_types = len(set(palabras))
            total_tokens += num_tokens
            total_types += num_types
            longitud_oraciones.append(num_tokens)

    if count > 0:
        media_longitud = total_tokens / count
        media_types = total_types / count
        media_longitud = 0
        media_types = 0


    print(f"Total de tokens en esas oraciones: {total_tokens}")
    print(f"Total de types (palabras únicas) en esas oraciones: {total_types}")
    print(f"Número de oraciones que contienen: {count}")
    #print(f"Media de longitud de las oraciones con : {media_longitud}")
    print("----------------------------------------")

    return count, total_tokens, total_types, media_types

contar_oraciones_con_palabra(content, 'alumnos')
contar_oraciones_con_palabra(content, 'profesores')
contar_oraciones_con_palabra(content, 'investigadores')
contar_oraciones_con_palabra(content, 'habitantes')
contar_oraciones_con_palabra(content, 'camareros')
contar_oraciones_con_palabra(content, 'ingenieros')
contar_oraciones_con_palabra(content, 'clientes')

contar_oraciones_con_palabra(content2, 'alumnos')
contar_oraciones_con_palabra(content2, 'profesores')
contar_oraciones_con_palabra(content2, 'investigadores')
contar_oraciones_con_palabra(content2, 'habitantes')
contar_oraciones_con_palabra(content2, 'camareros')
contar_oraciones_con_palabra(content2, 'ingenieros')
contar_oraciones_con_palabra(content2, 'clientes')

contar_oraciones_con_palabra(content3, 'alumnos')
contar_oraciones_con_palabra(content3, 'profesores')
contar_oraciones_con_palabra(content3, 'investigadores')
contar_oraciones_con_palabra(content3, 'habitantes')
contar_oraciones_con_palabra(content3, 'camareros')
contar_oraciones_con_palabra(content3, 'ingenieros')
contar_oraciones_con_palabra(content3, 'clientes')

contar_oraciones_con_palabra(content3, 'discapacitado')
contar_oraciones_con_palabra(content3, 'discapacitados')
contar_oraciones_con_palabra(content3, 'discapacitada')
contar_oraciones_con_palabra(content3, 'discapacitadas')

contar_oraciones_con_palabra(content2, 'discapacitado')
contar_oraciones_con_palabra(content2, 'discapacitados')
contar_oraciones_con_palabra(content2, 'discapacitada')
contar_oraciones_con_palabra(content2, 'discapacitadas')

contar_oraciones_con_palabra(content, 'discapacitado')
contar_oraciones_con_palabra(content, 'discapacitados')
contar_oraciones_con_palabra(content, 'discapacitada')
contar_oraciones_con_palabra(content, 'discapacitadas')

contar_oraciones_con_palabra(content3, 'minusválido')
contar_oraciones_con_palabra(content3, 'minusválidos')
contar_oraciones_con_palabra(content3, 'minusválida')
contar_oraciones_con_palabra(content3, 'minusválidas')

contar_oraciones_con_palabra(content2, 'minusválido')
contar_oraciones_con_palabra(content2, 'minusválidos')
contar_oraciones_con_palabra(content2, 'minusválida')
contar_oraciones_con_palabra(content2, 'minusválidas')

contar_oraciones_con_palabra(content, 'minusválido')
contar_oraciones_con_palabra(content, 'minusválidos')
contar_oraciones_con_palabra(content, 'minusválida')
contar_oraciones_con_palabra(content, 'minusválidas')

contar_oraciones_con_palabra(content3, 'inválido')
contar_oraciones_con_palabra(content3, 'inválidas')
contar_oraciones_con_palabra(content3, 'inválida')
contar_oraciones_con_palabra(content3, 'inválidos')

contar_oraciones_con_palabra(content2, 'inválido')
contar_oraciones_con_palabra(content2, 'inválidas')
contar_oraciones_con_palabra(content2, 'inválida')
contar_oraciones_con_palabra(content2, 'inválidos')

contar_oraciones_con_palabra(content, 'inválido')
contar_oraciones_con_palabra(content, 'inválidas')
contar_oraciones_con_palabra(content, 'inválida')
contar_oraciones_con_palabra(content, 'inválidos')

contar_oraciones_con_palabra(content3, 'disminuido')
contar_oraciones_con_palabra(content3, 'disminuidos')
contar_oraciones_con_palabra(content3, 'disminuida')
contar_oraciones_con_palabra(content3, 'disminuidas')

contar_oraciones_con_palabra(content2, 'disminuido')
contar_oraciones_con_palabra(content2, 'disminuidos')
contar_oraciones_con_palabra(content2, 'disminuida')
contar_oraciones_con_palabra(content2, 'disminuidas')

contar_oraciones_con_palabra(content, 'disminuido')
contar_oraciones_con_palabra(content, 'disminuidos')
contar_oraciones_con_palabra(content, 'disminuida')
contar_oraciones_con_palabra(content, 'disminuidas')

contar_oraciones_con_palabra(content3, 'retrasado')
contar_oraciones_con_palabra(content3, 'retrasados')
contar_oraciones_con_palabra(content3, 'retrasada')
contar_oraciones_con_palabra(content3, 'retrasadas')

contar_oraciones_con_palabra(content2, 'retrasado')
contar_oraciones_con_palabra(content2, 'retrasados')
contar_oraciones_con_palabra(content2, 'retrasada')
contar_oraciones_con_palabra(content2, 'retrasadas')

contar_oraciones_con_palabra(content, 'retrasado')
contar_oraciones_con_palabra(content, 'retrasados')
contar_oraciones_con_palabra(content, 'retrasada')
contar_oraciones_con_palabra(content, 'retrasadas')

contar_oraciones_con_palabra(content3, 'tetrapléjico')
contar_oraciones_con_palabra(content3, 'tetrapléjicos')
contar_oraciones_con_palabra(content3, 'tetrapléjica')
contar_oraciones_con_palabra(content3, 'tetrapléjicas')

contar_oraciones_con_palabra(content2, 'tetrapléjico')
contar_oraciones_con_palabra(content2, 'tetrapléjicos')
contar_oraciones_con_palabra(content2, 'tetrapléjica')
contar_oraciones_con_palabra(content2, 'tetrapléjicas')

contar_oraciones_con_palabra(content, 'tetrapléjico')
contar_oraciones_con_palabra(content, 'tetrapléjicos')
contar_oraciones_con_palabra(content, 'tetrapléjica')
contar_oraciones_con_palabra(content, 'tetrapléjicas')

def contar_oraciones_con_expresion(texto_input, expresion):
    oraciones = sent_tokenize(texto_input)

    count = 0
    total_tokens = 0
    total_types = 0
    longitud_oraciones = []

    patron = re.compile(expresion)

    for oracion in oraciones:
        if patron.search(oracion):
            palabras = word_tokenize(oracion)
            count += 1
            num_tokens = len(palabras)
            num_types = len(set(palabras))
            total_tokens += num_tokens
            total_types += num_types
            longitud_oraciones.append(num_tokens)


    if count > 0:
        media_longitud = total_tokens / count
        media_types = total_types / count
    else:
        media_longitud = 0
        media_types = 0

    print(f"Número de oraciones que contienen la expresión '{expresion}': {count}")
    print(f"Total de tokens en esas oraciones: {total_tokens}")
    print(f"Total de types (palabras únicas) en esas oraciones: {total_types}")
    print(f"Media de longitud de las oraciones con la expresión: {media_longitud}")

    return count, total_tokens, total_types, media_longitud, media_types

contar_oraciones_con_expresion(content, "padece discapacidad")

contar_oraciones_con_expresion(content, "padecen discapacidad")

contar_oraciones_con_expresion(content, "sufren discapacidad")

contar_oraciones_con_expresion(content, "sufre discapacidad")

contar_oraciones_con_expresion(content, "hombres de negocios")

contar_oraciones_con_expresion(content2, "padece discapacidad")

contar_oraciones_con_expresion(content2, "padecen discapacidad")

contar_oraciones_con_expresion(content2, "sufren discapacidad")

contar_oraciones_con_expresion(content2, "sufre discapacidad")

contar_oraciones_con_expresion(content2, "hombres de negocios")

contar_oraciones_con_expresion(content3, "padecen discapacidad")

contar_oraciones_con_expresion(content3, "padece discapacidad")

contar_oraciones_con_expresion(content3, "padecen discapacidad")

contar_oraciones_con_expresion(content3, "sufrir discapacidad")

contar_oraciones_con_expresion(content3, "sufre discapacidad")

contar_oraciones_con_expresion(content3, "sufren discapacidad")

contar_oraciones_con_expresion(content3, "hombres de negocios")

def calcular_estadisticas_texto_nltk(texto_input):
    oraciones = sent_tokenize(texto_input)

    total_oraciones = len(oraciones)
    total_tokens = 0
    total_types = set()
    longitud_oraciones = []

    for oracion in oraciones:
        palabras = word_tokenize(oracion)
        num_tokens = len(palabras)
        total_tokens += num_tokens
        total_types.update(palabras)
        longitud_oraciones.append(num_tokens)

    if total_oraciones > 0:
        media_longitud = total_tokens / total_oraciones
    else:
        media_longitud = 0

    num_types_total = len(total_types)

    print(f"Número total de oraciones: {total_oraciones}")
    print(f"Número total de tokens: {total_tokens}")
    print(f"Número total de types (palabras únicas): {num_types_total}")
    print(f"Media de longitud de las oraciones (tokens): {media_longitud}")

    return total_oraciones, total_tokens, num_types_total, media_longitud

calcular_estadisticas_texto_nltk(content)

calcular_estadisticas_texto_nltk(content2)

calcular_estadisticas_texto_nltk(content3)