# -*- coding: utf-8 -*-
"""Funcion metricas por etiqueta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hZwTSzVc2RSDboMoYanLgGseWiOP9vx5
"""



# Se calculan las métricas por etiqueta

def calculate_metrics_with_overall(predictions, labels, label_names=None):
    # Alineamos las predicciones y etiquetas
    aligned_preds, aligned_labels = align_labels(predictions, labels)

    # Métricas por etiqueta
    precision_per_label = precision_score(aligned_labels, aligned_preds, average=None)
    recall_per_label = recall_score(aligned_labels, aligned_preds, average=None)
    f1_per_label = f1_score(aligned_labels, aligned_preds, average=None)

    # Métricas globales (F1 macro y micro)
    f1_macro = f1_score(aligned_labels, aligned_preds, average="macro")
    f1_micro = f1_score(aligned_labels, aligned_preds, average="micro")

    # Resultados por etiqueta
    metrics_per_label = {}
    for i, (precision, recall, f1) in enumerate(zip(precision_per_label, recall_per_label, f1_per_label)):
        label = label_names[i] if label_names else f"Etiqueta {i}"
        metrics_per_label[label] = {
            "precision": precision,
            "recall": recall,
            "f1": f1
        }

    # Agregar métricas globales
    metrics_per_label["Overall"] = {
        "f1_macro": f1_macro,
        "f1_micro": f1_micro
    }

    return metrics_per_label

# Ejemplo de uso
predictions = [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
               [1, 0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]]

labels = [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
          [1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]]

#label_names = [f"Clase {i}" for i in range(16)]
etiquetas = ['alu', 'bus', 'cam', 'cl', 'dis1', 'dis2', 'dis3', 'dis4', 'dis5', 'dis6', 'hab', 'ing', 'inv', 'profs', 'vdis1', 'vdis2']

metrics = calculate_metrics_with_overall(predictions, labels, etiquetas)

# Imprimir resultados
for label, metric in metrics.items():
    if label == "Overall":
        print(f"{label}: F1 Macro={metric['f1_macro']:.2f}, F1 Micro={metric['f1_micro']:.2f}")
    else:
        print(f"{label}: Precision={metric['precision']:.2f}, Recall={metric['recall']:.2f}, F1={metric['f1']:.2f}")

